/* PROCEDURES DE INSERÇÃO */

/******************* TABELA CINEMA ********************/
DELIMITER $$
CREATE PROCEDURE SP_INSERIR_CINEMA (IN CNPJ_DO_CINEMA VARCHAR(45), RAZAO_SOCIAL VARCHAR(100), NOME_FANTASIA VARCHAR(45), CAPACIDADE_CINE INT)
BEGIN
	IF EXISTS (SELECT CNPJ FROM CINEMA WHERE CNPJ = CNPJ_DO_CINEMA)
	THEN
		SELECT 'CINEMA JÁ CADASTRADO';
	ELSE
		INSERT INTO CINEMA VALUES (NULL, CNPJ_DO_CINEMA, RAZAO_SOCIAL, NOME_FANTASIA, CAPACIDADE_CINE);
	END IF ;
END $$
DELIMITER ;

/******************* TABELA CLIENTE ********************/
DELIMITER $$
CREATE PROCEDURE SP_INSERIR_CLIENTE (IN NOME_CLIENTE VARCHAR(45), CPF_CLIENTE VARCHAR(20), SEXO ENUM('M','F'), DATA_NASCIMENTO DATE, EMAIL_CLIENTE VARCHAR(100))
BEGIN
	IF EXISTS (SELECT CPF FROM CLIENTE WHERE CPF = CPF_CLIENTE)
	THEN
		SELECT 'CLIENTE JÁ CADASTRADO';
	ELSE
		INSERT INTO CLIENTE VALUES (NULL, NOME_CLIENTE, CPF_CLIENTE, SEXO, DATA_NASCIMENTO, EMAIL_CLIENTE);
	END IF;
END $$
DELIMITER ;

/******************* TABELA PRODUTO ********************/
DELIMITER $$
CREATE PROCEDURE SP_INSERIR_PRODUTO (IN NOME_PRODUTO VARCHAR(45), CATEGORIA_PRODUTO VARCHAR(45), DESCRICAO_PRODUTO VARCHAR(45), VALOR_BRUTO DECIMAL(10,2))
BEGIN
	IF EXISTS (SELECT NOMEPRODUTO FROM PRODUTO WHERE NOMEPRODUTO = NOME_PRODUTO)
	THEN
		SELECT 'PRODUTO JÁ CADASTRADO';
	ELSE
		INSERT INTO PRODUTO VALUES (NULL, NOME_PRODUTO, CATEGORIA_PRODUTO, DESCRICAO_PRODUTO, VALOR_BRUTO);
	END IF ;
END $$
DELIMITER ;

/******************* TABELA SALA ********************/
DELIMITER $$
CREATE PROCEDURE SP_INSERIR_SALA (IN TIPO_SALA VARCHAR(45), NUMERO_SALA INT)
BEGIN
	IF EXISTS (SELECT TIPOSALA FROM SALA WHERE TIPOSALA = TIPO_SALA AND NUMEROSALA = NUMERO_SALA)
	THEN
		SELECT 'SALA JÁ CADASTRADA';
	ELSE
		INSERT INTO SALA VALUES (NULL, TIPO_SALA, NUMERO_SALA);
	END IF ;
END $$
DELIMITER ;

/******************* TABELA INGRESSO ********************/
DELIMITER $$
CREATE PROCEDURE SP_INSERIR_INGRESSO (IN TIPO_INGRESSO VARCHAR(45), VALOR_INGRESSO DECIMAL(10,2))
BEGIN
	IF EXISTS (SELECT TIPOINGRESSO FROM INGRESSO WHERE TIPOINGRESO = TIPO_INGRESSO)
	THEN
		SELECT 'INGRESSO JÁ CADASTRADO';
	ELSE
		INSERT INTO INGRESSO VALUES (NULL, TIPO_INGRESSO, VALOR_INGRESSO);
	END IF ;
END $$
DELIMITER ;

/******************* TABELA FUNCIONARIO ********************/
DELIMITER $$
CREATE PROCEDURE SP_INSERIR_FUNCIONARIO (IN MATRICULA_FUNCIONARIO VARCHAR(45), NOME_FUNCIONARIO VARCHAR(45), ID_CLIENTE INT, ID_CINEMA INT)
BEGIN
	IF EXISTS (SELECT MATFUNCIONARIO FROM FUNCIONARIO WHERE MATFUNCIONARIO = MATRICULA_FUNCIONARIO)
	THEN
		SELECT 'FUNCIONARIO JÁ CADASTRADO';
	ELSE
		INSERT INTO FUNCIONARIO VALUES (NULL, MATRICULA_FUNCIONARIO, NOME_FUNCIONARIO, ID_CLIENTE, ID_CINEMA);
	END IF ;
END $$
DELIMITER ;

/******************* TABELA ENDERECO ********************/
DELIMITER $$
CREATE PROCEDURE SP_INSERIR_ENDERECO (IN LOGRADOURO VARCHAR(45), BAIRRO VARCHAR(45), CIDADE VARCHAR(45), ESTADO CHAR(2), 
									  CEP VARCHAR(20), ID_CINEMA INT, ID_FUNCIONARIO INT, ID_CLIENTE INT)
BEGIN
	INSERT INTO ENDERECO VALUES(NULL, LOGRADOURO, BAIRRO, CIDADE, ESTADO, CEP, ID_CINEMA, ID_FUNCIONARIO, ID_CLIENTE);
END $$
DELIMITER ;

/******************* TABELA TELEFONE ********************/
DELIMITER $$
CREATE PROCEDURE SP_INSERIR_TELEFONE (IN TIPO_TELEFONE ENUM ('CEL', 'RES', 'COM'), NUMERO_TELEFONE VARCHAR(20), ID_CINEMA INT,
									  ID_FUNCIONARIO INT, ID_CLIENTE INT)
BEGIN
	IF EXISTS (SELECT NUMEROTELEFONE FROM TELEFONE WHERE NUMEROTELEFONE = NUMERO_TELEFONE)
	THEN
		SELECT 'TELEFONE JÁ CADASTRADO';
	ELSE
		INSERT INTO TELEFONE VALUES (NULL, TIPO_TELEFONE, NUMERO_TELEFONE, ID_CINEMA, ID_FUNCIONARIO, ID_CLIENTE);
	END IF ;
END $$
DELIMITER ;

/******************* TABELA SERVICO ********************/
DELIMITER $$
CREATE PROCEDURE SP_INSERIR_SERVICO (IN TIPO_SERVICO VARCHAR(45), DESCRICAO_SERVICO VARCHAR(45), ID_CINEMA INT,
									 ID_PRODUTO INT, ID_SALA INT, ID_INGRESSO INT)
BEGIN
	INSERT INTO SERVICO VALUES (NULL, TIPO_SERVICO, DESCRICAO_SERVICO, ID_CINEMA, ID_PRODUTO, ID_SALA, ID_INGRESSO);
END $$
DELIMITER ;

/******************* TABELA PEDIDO ********************/
DELIMITER $$
CREATE PROCEDURE SP_INSERIR_PEDIDO(IN ID_CLIENTE INT, ID_SERVICO INT)
BEGIN
	INSERT INTO PEDIDO VALUES (NULL, ID_CLIENTE, ID_SERVICO);
END $$
DELIMITER ;

/******************* TABELA SESSAO ********************/
DELIMITER $$
CREATE PROCEDURE SP_INSERIR_SESSAO(IN DATA_SESSAO DATE, HORA_SESSAO TIME, ID_SALA INT)
BEGIN
	INSERT INTO SESSAO VALUES (NULL, DATA_SESSAO, HORA_SESSAO, ID_SALA);
END $$
DELIMITER ;

/******************* TABELA FILME ********************/
DELIMITER $$
CREATE PROCEDURE SP_INSERIR_FILME(IN TITULO_FILME VARCHAR(45), GENERO_FILME VARCHAR(45),
								  DESCRICAO_FILME VARCHAR(150), CLASSIFICACAO_FILME VARCHAR(20), 
								  DURACAO_FILME VARCHAR(10), ID_INGRESSO INT, ID_SESSAO INT)
BEGIN
	INSERT INTO ENDERECO VALUES(NULL, TITULO_FILME, GENERO_FILME, DESCRICAO_FILME, CLASSIFICACAO_FILME, DURACAO_FILME,
								ID_INGRESSO, ID_SESSAO);
END $$
DELIMITER ;

/******************* TABELA PAGAMENTO ********************/
DELIMITER $$
CREATE PROCEDURE SP_INSERIR_PAGAMENTO(IN TIPOPAGAMENTO ENUM('CREDITO', 'DEBITO', 'PIX', 'A VISTA'),
									  VALOR_PAGAMENTO DECIMAL(10,2), DATA_PAGAMENTO DATE, ID_PEDIDO INT)
BEGIN
	INSERT INTO PAGAMENTO VALUES (NULL, TIPOPAGAMENTO, VALOR_PAGAMENTO, DATA_PAGAMENTO, ID_PEDIDO);
END $$
DELIMITER ;