/* PROCEDURES DE SELEÇÃO */

/******************* TABELA CINEMA ********************/
DELIMITER $$
CREATE PROCEDURE SP_SELECAO_CINEMA()
BEGIN
	SELECT * FROM CINEMA;
END $$
DELIMITER ;

CALL CINEMA.SP_SELECAO_CINEMA();

/******************* TABELA CLIENTE ********************/
DELIMITER $$
CREATE PROCEDURE SP_SELECAO_CLIENTE()
BEGIN
	SELECT * FROM CLIENTE;
END $$
DELIMITER ;

CALL CINEMA.SP_SELECAO_CLIENTE();


/******************* TABELA EMPREGADO ********************/
DELIMITER $$
CREATE PROCEDURE SP_SELECAO_EMPREGADO()
BEGIN
	SELECT * FROM EMPREGADO;
END $$
DELIMITER ;

CALL CINEMA.SP_SELECAO_EMPREGADO();


/******************* TABELA ENDERECO ********************/
DELIMITER $$
CREATE PROCEDURE SP_SELECAO_ENDERECO()
BEGIN
	SELECT * FROM ENDERECO;
END $$
DELIMITER ;

CALL CINEMA.SP_SELECAO_ENDERECO();

/******************* TABELA FILME ********************/
DELIMITER $$
CREATE PROCEDURE SP_SELECAO_FILME()
BEGIN
	SELECT * FROM FILME;
END $$
DELIMITER ;

CALL CINEMA.SP_SELECAO_FILME();

/******************* TABELA FUNCIONARIO ********************/
DELIMITER $$
CREATE PROCEDURE SP_SELECAO_FUNCIONARIO()
BEGIN
	SELECT * FROM FUNCIONARIO;
END $$
DELIMITER ;

CALL CINEMA.SP_SELECAO_FUNCIONARIO();

/******************* TABELA INGRESSO ********************/
DELIMITER $$
CREATE PROCEDURE SP_SELECAO_INGRESSO()
BEGIN
	SELECT * FROM INGRESSO;
END $$
DELIMITER ;

CALL CINEMA.SP_SELECAO_INGRESSO();

/******************* TABELA PAGAMENTO ********************/
DELIMITER $$
CREATE PROCEDURE SP_SELECAO_PAGAMENTO()
BEGIN
	SELECT * FROM PAGAMENTO;
END $$
DELIMITER ;

CALL CINEMA.SP_SELECAO_PAGAMENTO();

/******************* TABELA PEDIDO ********************/
DELIMITER $$
CREATE PROCEDURE SP_SELECAO_PEDIDO()
BEGIN
	SELECT * FROM PEDIDO;
END $$
DELIMITER ;

CALL CINEMA.SP_SELECAO_PEDIDO();


/******************* TABELA PRODUTO ********************/
DELIMITER $$
CREATE PROCEDURE SP_SELECAO_PRODUTO()
BEGIN
	SELECT * FROM PRODUTO;
END $$
DELIMITER ;

CALL CINEMA.SP_SELECAO_PRODUTO();

/******************* TABELA SALA ********************/
DELIMITER $$
CREATE PROCEDURE SP_SELECAO_SALA()
BEGIN
	SELECT * FROM SALA;
END $$
DELIMITER ;

CALL CINEMA.SP_SELECAO_SALA();

/******************* TABELA SERVICO ********************/
DELIMITER $$
CREATE PROCEDURE SP_SELECAO_SERVICO()
BEGIN
	SELECT * FROM SERVICO;
END $$
DELIMITER ;

CALL CINEMA.SP_SELECAO_SERVICO();

/******************* TABELA SESSAO ********************/
DELIMITER $$
CREATE PROCEDURE SP_SELECAO_SESSAO()
BEGIN
	SELECT * FROM SESSAO;
END $$
DELIMITER ;

CALL CINEMA.SP_SELECAO_SESSAO();

/******************* TABELA TELEFONE ********************/
DELIMITER $$
CREATE PROCEDURE SP_SELECAO_TELEFONE()
BEGIN
	SELECT * FROM TELEFONE;
END $$
DELIMITER ;

CALL CINEMA.SP_SELECAO_TELEFONE();