/* CRIANDO O BANCO */
CREATE DATABASE CINEMA;

/* SELECIONANDO O BANCO */
USE CINEMA;


/*CRIANDO AS TABELAS DO BANCO*/
CREATE TABLE CINEMA (
	IDCINEMA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	CNPJ VARCHAR(45) NOT NULL UNIQUE,
	RAZAOSOCIAL VARCHAR(100) NOT NULL,
	NOMEFANTASIA VARCHAR(45) NOT NULL,
	CAPACIDADE INT NOT NULL
);

CREATE TABLE CLIENTE (
	IDCLIENTE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOMECLIENTE VARCHAR(45) NOT NULL,
	CPF VARCHAR(20) NOT NULL UNIQUE,
	SEXO ENUM('M','F'),
	DATANASC DATE,
	EMAIL VARCHAR(100) UNIQUE
);

CREATE TABLE PRODUTO (
	IDPRODUTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NOMEPRODUTO VARCHAR(45) NOT NULL,
	CATPRODUTO VARCHAR(45) NOT NULL,
	DESCPRODUTO VARCHAR(45) NOT NULL, 
	VALORBRUTO DECIMAL(10,2) NOT NULL
);

CREATE TABLE SALA (
	IDSALA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	TIPOSALA VARCHAR(45) NOT NULL,
	NUMEROSALA INT NOT NULL
);

CREATE TABLE INGRESSO (
	IDINGRESSO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	TIPOINGRESSO ENUM('2D', '3D', 'XD', 'D-BOX'),
	VALORINGRESSO DECIMAL(10,2)
);

CREATE TABLE FUNCIONARIO (
	IDFUNCIONARIO INT  PRIMARY KEY AUTO_INCREMENT,
	MATFUNCIONARIO VARCHAR(45) NOT NULL,
	NOMEFUNCIONARIO VARCHAR(45) NOT NULL,
	ID_CLIENTE INT,
	ID_CINEMA INT,
	CONSTRAINT FK_CLIENTE_FUNCIONARIO FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_CINEMA_FUNCIONARIO FOREIGN KEY (ID_CINEMA) REFERENCES CINEMA(IDCINEMA)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE ENDERECO (
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	LOGRADOURO VARCHAR(45),
	BAIRRO VARCHAR(45),
	CIDADE VARCHAR(45),
	ESTADO CHAR(2),
	CEP VARCHAR(20),
	ID_CINEMA INT,
	ID_FUNCIONARIO INT,
	ID_CLIENTE INT,
	CONSTRAINT FK_CINEMA_ENDERECO FOREIGN KEY (ID_CINEMA) REFERENCES CINEMA(IDCINEMA)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_FUNCIONARIO_ENDERECO FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_CLIENTE_ENDERECO FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE TELEFONE (
	IDTELEFONE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	TIPOTELEFONE ENUM ('CEL', 'RES', 'COM'),
	NUMEROTELEFONE VARCHAR(20),
	ID_CINEMA INT,
	ID_FUNCIONARIO INT,
	ID_CLIENTE INT,
	CONSTRAINT FK_CINEMA_TELEFONE FOREIGN KEY (ID_CINEMA) REFERENCES CINEMA(IDCINEMA)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_FUNCIONARIO_TELEFONE FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO(IDFUNCIONARIO)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_CLIENTE_TELEFONE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SERVICO (
	IDSERVICO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	TIPOSERVICO VARCHAR(45),
	DESCSERVICO VARCHAR(45),
	ID_CINEMA INT,
	ID_PRODUTO INT,
	ID_SALA INT,
	ID_INGRESSO INT,
	CONSTRAINT FK_CINEMA_SERVICO FOREIGN KEY (ID_CINEMA) REFERENCES CINEMA(IDCINEMA)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_PRODUTO_SERVICO FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(IDPRODUTO)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_SALA_SERVICO FOREIGN KEY (ID_SALA) REFERENCES SALA(IDSALA)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_INGRESSO_SERVICO FOREIGN KEY (ID_INGRESSO) REFERENCES INGRESSO(IDINGRESSO)
);

CREATE TABLE PEDIDO (
	IDPEDIDO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ID_CLIENTE INT,
	ID_SERVICO INT,
	CONSTRAINT FK_CLIENTE_PEDIDO FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_SERVICO_PEDIDO FOREIGN KEY (ID_SERVICO) REFERENCES SERVICO(IDSERVICO)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE SESSAO (
	IDSESSAO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	DATASESSAO DATE,
	HORASESSAO TIME,
	ID_SALA INT,
	CONSTRAINT FK_SALA_SESSAO FOREIGN KEY (ID_SALA) REFERENCES SALA(IDSALA)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE FILME (
	IDFILME INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	TITULOFILME VARCHAR(45) NOT NULL,
	GENEROFILME VARCHAR(45) NOT NULL,
	DESCFILME VARCHAR(100) NOT NULL,
	CLASSIFICACAOFILME VARCHAR(20) NOT NULL,
	DURACAOFILME VARCHAR(10) NOT NULL,
	ID_INGRESSO INT,
	ID_SESSAO INT,
	CONSTRAINT FK_INGRESSO_FILME FOREIGN KEY (ID_INGRESSO) REFERENCES INGRESSO(IDINGRESSO)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT FK_SESSAO_FILME FOREIGN KEY (ID_SESSAO) REFERENCES SESSAO(IDSESSAO)
	ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE PAGAMENTO (
	IDPAGAMENTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	TIPOPAGAMENTO ENUM ('CREDITO', 'DEBITO', 'PIX', 'A VISTA'),
	VALORPAGAMENTO DECIMAL(10,2),
	DATAPAGAMENTO DATE,
	ID_PEDIDO INT,
	CONSTRAINT FK_PEDIDO_PAGAMENTO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(IDPEDIDO)
);

